// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtY1YfB0N9ubC5DuYzsgw0WZZXHF_ZOAk',
    appId: '1:659229785565:web:6c4ea0c7621f197aa90a34',
    messagingSenderId: '659229785565',
    projectId: 'fir-cafb1',
    authDomain: 'fir-cafb1.firebaseapp.com',
    storageBucket: 'fir-cafb1.appspot.com',
    measurementId: 'G-X97VS753KV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAi-lbCJy3D871tS1N5zIgxbCTlXw0SiZ4',
    appId: '1:659229785565:android:bcf2619da775f816a90a34',
    messagingSenderId: '659229785565',
    projectId: 'fir-cafb1',
    storageBucket: 'fir-cafb1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnHHLY1gw1EWtXIAnSzEyLlUaECxx07uc',
    appId: '1:659229785565:ios:9296d07880d8620fa90a34',
    messagingSenderId: '659229785565',
    projectId: 'fir-cafb1',
    storageBucket: 'fir-cafb1.appspot.com',
    iosBundleId: 'com.example.firebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDtY1YfB0N9ubC5DuYzsgw0WZZXHF_ZOAk',
    appId: '1:659229785565:web:b8bcf1d8db8de175a90a34',
    messagingSenderId: '659229785565',
    projectId: 'fir-cafb1',
    authDomain: 'fir-cafb1.firebaseapp.com',
    storageBucket: 'fir-cafb1.appspot.com',
    measurementId: 'G-JVHY14Q294',
  );
}
